runtime: nodejs16

instance_class: F2

env_variables:
    BUCKET_NAME: "enron-website"

handlers:
    - url: /
      static_files: dist/enron-website/index.html
      upload: dist/enron-website/index.html

    - url: /
      static_dir: dist/enron-website
